### ISSUE TITLE
🛑 TRN Generation API Test is down

### ISSUE THREAD

**Issue by teacher-services-upptime** [DFE-Digital/teacher-services-upptime#564]
In [`747dd16`](https://github.com/DFE-Digital/teacher-services-upptime/commit/747dd1607dbc1b36edac4a860261da8c7fec33c8
), TRN Generation API Test (https://trn-generation-api.education.gov.uk/health123) was **down**:
- HTTP code: 404
- Response time: 156 ms

**Comment by saliceti** [comment]
This was a test website
